### ISSUE TITLE
Typo with Reaper options

### ISSUE THREAD

**Issue by xenophire** [MKhayle/XIVComboPlugin#186]
I had just dinged and was looking at the different options for some abilities I got and was able to find Soul Lemure's Feature just fine but couldn't for the life of me find the one for Lemure's Scythe. I ticked the Scythe one anyway and it changed Nightmare Scythe into Lemure's Scythe rather than Slice like stated in the description.

**Comment by MKhayle** [comment]
This was fixed a year ago in https://github.com/MKhayle/XIVComboPlugin/commit/039704a918a961df5ea61052feda76e1ac8c7d86 

Thanks for the report, though!
