### ISSUE TITLE
Scholar: Sacred Soil - Aetherflow

### ISSUE THREAD

**Issue by naTlatsyrC** [MKhayle/XIVComboPlugin#231]
Could the implementation of Lustrous Aetherflow or Indomitable Aetherflow be added to Sacred Soil too? 
(own option of course)

Thanks!

**Comment by MKhayle** [comment]
Hello, thanks for the suggestion! 

This feature has been added as "Sacred Soil Aetherflow" in https://github.com/MKhayle/XIVComboPlugin/commit/b8856f0e05ff4170842b98de807057d9306a9791.
