### ISSUE TITLE
Can we get a more detailed instruction for installing this?

### ISSUE THREAD

**Issue by IndigoVagrant** [MKhayle/XIVComboPlugin#237]
I don't understand the instructions. I tried using the Json link in the Dalamud settings ---> experimental ---> Custom Plugins Repo.   Does not appear to do anything. 

This is the link I addedL
https://github.com/daemitus/MyDalamudPlugins/raw/master/pluginmaster.json

**Comment by MKhayle** [comment]
You need to confirm adding the repository, and then manually save the changes you made. 

See this:
![image](https://github.com/MKhayle/XIVComboPlugin/assets/4359469/831dcb26-3d17-4264-b84f-fb8dc8e42eee)

**Comment by IndigoVagrant** [comment]
It appears that I had to enable "Get Plugin Testing Buiilds". After that your plugin appeared in the list of available plugins to be installed.

**Comment by MKhayle** [comment]
Weird, but as long as it works it's all good. I'll look that up if someone else has the issue.

**Comment by IndigoVagrant** [comment]
A lot of people need step by step instructions to figure out installing this.  Hopefully the issue I ran into can help you with that. 
https://github.com/attickdoor/XIVComboPlugin/issues/282

**Comment by lovelydumpling** [comment]
"Get Plugin Testing Builds" should not be necessary, I did not have to do this. 

I do often forget to click the save button in the custom repositories list, but otherwise I'm not sure why the plugin would not appear for install.
