### ISSUE TITLE
#132 Prominence Combo – not changing

### ISSUE THREAD

**Issue by Mouseattigan** [MKhayle/XIVComboPlugin#238]
When on my hotbar, Prominence changes into Total Eclipse, but once pressed it doesn't turn into Prominence to continue the AoE rotation – it stays as Total Eclipse. I'm not under-level for the ability, and Prominence works in a vanilla state.

**Comment by MKhayle** [comment]
Hello,

I can't reproduce that issue. 
Have you actually been hitting any targets with Total Eclipse? 
If you're missing your target (ie level difference on a lvl 90 Training Dummy), you won't get the combo starting.

**Comment by Mouseattigan** [comment]
Oh! I see! v//v); That is definitely user error/lack of observance on my part, oops. 'twas a feature I hadn't noticed.

Sorry for taking up your time. (っ °Д °;)っ

**Comment by MKhayle** [comment]
No worries!
